@shiko_profile_provider.Api_HostAddress = https://localhost:4443

### Create profile
POST {{shiko_profile_provider.Api_HostAddress}}/api/profiles
Accept: application/json
Content-Type: application/json

{  
  "firstname": "Maria",
  "lastname": "Magnell",
  "phonenumber": "123",
  "description": "ABC"
}

### Get All profiles
GET {{shiko_profile_provider.Api_HostAddress}}/api/profile
Accept: application/json
Authorization: Bearer {{token}}

### Get profile by id
GET {{shiko_profile_provider.Api_HostAddress}}/api/profile/
Accept: application/json

### Update profile
PUT {{shiko_profile_provider.Api_HostAddress}}/api/profiles/
Accept: application/json
Content-Type: application/json

{
  "firstname": "Tommy",
  "lastname": "Magnell",
  "phonenumber": "321",
  "description": "ABC"
}

### Delete profile
DELETE {{shiko_profile_provider.Api_HostAddress}}/api/profile/